import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en',    name: 'English',          native: 'English',       dir: 'ltr', flag: '🇬🇧' },
  { code: 'sw',    name: 'Swahili',          native: 'Kiswahili',     dir: 'ltr', flag: '🇰🇪' },
  { code: 'zh',    name: 'Mandarin Chinese', native: '中文',           dir: 'ltr', flag: '🇨🇳' },
  { code: 'hi',    name: 'Hindi',            native: 'हिन्दी',         dir: 'ltr', flag: '🇮🇳' },
  { code: 'es',    name: 'Spanish',          native: 'Español',       dir: 'ltr', flag: '🇪🇸' },
  { code: 'ar',    name: 'Arabic',           native: 'العربية',       dir: 'rtl', flag: '🇸🇦' },
  { code: 'fr',    name: 'French',           native: 'Français',      dir: 'ltr', flag: '🇫🇷' },
  { code: 'bn',    name: 'Bengali',          native: 'বাংলা',          dir: 'ltr', flag: '🇧🇩' },
  { code: 'pt',    name: 'Portuguese',       native: 'Português',     dir: 'ltr', flag: '🇧🇷' },
  { code: 'ru',    name: 'Russian',          native: 'Русский',       dir: 'ltr', flag: '🇷🇺' },
  { code: 'ur',    name: 'Urdu',             native: 'اردو',           dir: 'rtl', flag: '🇵🇰' },
];

export const translations = {
  en: {
    // Navigation
    nav_about: 'About',
    nav_menu: 'Menu',
    nav_reservations: 'Reservations',
    nav_gallery: 'Gallery',
    nav_contact: 'Contact',
    nav_careers: 'Careers',
    nav_home: 'Home',
    nav_order: 'Order',
    nav_offers: 'Offers',
    nav_sign_in: 'Sign In',
    nav_create_account: 'Create Account',
    nav_my_bookings: 'My Bookings',
    nav_rate_us: 'Rate Us',
    nav_client_view: 'Client View',
    // Staff Portal Nav
    nav_dashboard: 'Dashboard',
    nav_kds: 'KDS',
    nav_inventory: 'Inventory',
    nav_bookings: 'Bookings',
    nav_specialties: 'Specialties',
    nav_orders: 'Orders',
    nav_employees: 'Employees',
    nav_admin_console: 'Admin Console',
    nav_sign_out: 'Sign Out',
    nav_reset_system: 'Reset System',
    portal_admin: 'Admin Portal',
    portal_staff: 'Staff Portal',
    // Footer
    footer_navigate: 'Navigate',
    footer_hours: 'Hours',
    footer_newsletter: 'Newsletter',
    footer_newsletter_desc: 'Get exclusive offers and event invites.',
    footer_email_placeholder: 'Email address',
    footer_join: 'Join',
    footer_copyright: '© 2026 Kolay Restaurant. All rights reserved.',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Use',
    footer_staff_portal: 'Staff Portal',
    footer_language: 'Language',
    footer_every_day: 'Every Day',
    footer_open_247: 'Open 24/7',
    footer_tagline: 'Artisan culinary experiences crafted for those who appreciate the finer things in life.',
    // Home Page
    home_hero_subtitle: 'An Extraordinary Culinary Journey',
    home_hero_title_1: 'Where Every Dish',
    home_hero_title_2: 'Tells a Story',
    home_hero_desc: 'Experience the perfect harmony of flavors, ambiance and service. We create memories that last a lifetime.',
    home_reserve_table: 'Reserve a Table',
    home_explore_menu: 'Explore Menu',
    home_guests_served: 'Guests Served',
    home_years_excellence: 'Years of Excellence',
    home_awards_won: 'Awards Won',
    home_chefs: 'Master Chefs',
    // About
    about_title: 'Our Story',
    about_subtitle: 'A Legacy of Culinary Excellence',
    about_desc_1: 'Founded with a passion for extraordinary cuisine, Kolay Restaurant has been a cornerstone of fine dining since our inception. Every dish we create is a testament to our commitment to quality, creativity, and the timeless art of gastronomy.',
    about_desc_2: 'Our chefs source the finest ingredients globally, blending traditional techniques with modern innovation to create unforgettable dining experiences.',
    about_award: 'Michelin Star Restaurant',
    about_commitment: 'Our Commitment',
    about_commitment_desc: 'We believe every meal should be an experience. From farm-fresh ingredients to meticulous plating, excellence is not just our standard - it\'s our promise.',
    // Menu Section
    menu_title: 'Our Menu',
    menu_subtitle: 'Culinary Masterpieces',
    menu_explore: 'Explore Full Menu',
    menu_order_online: 'Order Online',
    // Gallery
    gallery_title: 'Gallery',
    gallery_subtitle: 'A Visual Feast',
    // Reservations
    reservations_title: 'Reservations',
    reservations_subtitle: 'Reserve Your Table',
    reservation_name: 'Full Name',
    reservation_email: 'Email Address',
    reservation_phone: 'Phone Number',
    reservation_date: 'Date',
    reservation_time: 'Time',
    reservation_guests: 'Number of Guests',
    reservation_notes: 'Special Requests',
    reservation_submit: 'Book Table',
    reservation_success: 'Reservation confirmed!',
    reservation_select_guests: 'Select guests',
    // Login / Register
    login_title: 'Welcome Back',
    login_subtitle: 'Sign in to your account',
    login_email: 'Email',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_no_account: 'Don\'t have an account?',
    login_register: 'Create one',
    register_title: 'Create Account',
    register_subtitle: 'Join Kolay Restaurant',
    register_username: 'Username',
    register_email: 'Email',
    register_password: 'Password',
    register_confirm: 'Confirm Password',
    register_btn: 'Create Account',
    register_have_account: 'Already have an account?',
    register_sign_in: 'Sign In',
    // Dashboard
    dashboard_title: 'Dashboard',
    dashboard_total_orders: 'Total Orders',
    dashboard_revenue: 'Revenue',
    dashboard_customers: 'Customers',
    dashboard_avg_order: 'Avg. Order',
    dashboard_recent_orders: 'Recent Orders',
    dashboard_low_stock: 'Low Stock Items',
    // POS
    pos_title: 'Point of Sale',
    pos_search: 'Search items...',
    pos_order_summary: 'Order Summary',
    pos_total: 'Total',
    pos_place_order: 'Place Order',
    pos_clear: 'Clear',
    pos_categories: 'Categories',
    // KDS
    kds_title: 'Kitchen Display',
    kds_new: 'New',
    kds_preparing: 'Preparing',
    kds_ready: 'Ready',
    kds_mark_ready: 'Mark Ready',
    // Inventory
    inventory_title: 'Inventory',
    inventory_add_item: 'Add Item',
    inventory_search: 'Search inventory...',
    inventory_item_name: 'Item Name',
    inventory_quantity: 'Quantity',
    inventory_unit: 'Unit',
    inventory_low_stock: 'Low Stock',
    // Bookings
    bookings_title: 'My Bookings',
    bookings_upcoming: 'Upcoming',
    bookings_past: 'Past',
    bookings_cancel: 'Cancel',
    bookings_no_bookings: 'No bookings found',
    // Careers
    careers_title: 'Careers',
    careers_subtitle: 'Join Our Team',
    careers_apply: 'Apply Now',
    careers_no_positions: 'No open positions at this time.',
    // General
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    add: 'Add',
    update: 'Update',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
  },

  sw: {
    nav_about: 'Kuhusu',
    nav_menu: 'Menyu',
    nav_reservations: 'Mapaji',
    nav_gallery: 'Picha',
    nav_contact: 'Wasiliana',
    nav_careers: 'Kazi',
    nav_home: 'Nyumbani',
    nav_order: 'Agiza',
    nav_offers: 'Punguzo',
    nav_sign_in: 'Ingia',
    nav_create_account: 'Fungua Akaunti',
    nav_my_bookings: 'Miadi Yangu',
    nav_rate_us: 'Tuambie',
    nav_client_view: 'Mtazamo wa Mteja',
    nav_dashboard: 'Dashibodi',
    nav_kds: 'KDS',
    nav_inventory: 'Hifadhi',
    nav_bookings: 'Miadi',
    nav_specialties: 'Maalum',
    nav_orders: 'Maagizo',
    nav_employees: 'Wafanyakazi',
    nav_admin_console: 'Dashibodi ya Admin',
    nav_sign_out: 'Toka',
    nav_reset_system: 'Weka Upya Mfumo',
    portal_admin: 'Bandari ya Admin',
    portal_staff: 'Bandari ya Wafanyakazi',
    footer_navigate: 'Viungo',
    footer_hours: 'Masaa',
    footer_newsletter: 'Jarida',
    footer_newsletter_desc: 'Pata matoleo maalum na mialiko ya matukio.',
    footer_email_placeholder: 'Anwani ya barua pepe',
    footer_join: 'Jiunge',
    footer_copyright: '© 2026 Kolay Restaurant. Haki zote zimehifadhiwa.',
    footer_privacy: 'Sera ya Faragha',
    footer_terms: 'Masharti ya Matumizi',
    footer_staff_portal: 'Bandari ya Wafanyakazi',
    footer_language: 'Lugha',
    footer_every_day: 'Kila Siku',
    footer_open_247: 'Wazi 24/7',
    footer_tagline: 'Uzoefu wa upishi bora ulioundwa kwa wale wanaothamini mambo mazuri maishani.',
    home_hero_subtitle: 'Safari ya Kipekee ya Upishi',
    home_hero_title_1: 'Ambapo Kila Sahani',
    home_hero_title_2: 'Inasimulia Hadithi',
    home_hero_desc: 'Pata maelewano kamili ya ladha, mazingira na huduma. Tunaunda kumbukumbu zinazodumu maisha yote.',
    home_reserve_table: 'Hifadhi Meza',
    home_explore_menu: 'Chunguza Menyu',
    home_guests_served: 'Wageni Waliohudumiwa',
    home_years_excellence: 'Miaka ya Ubora',
    home_awards_won: 'Tuzo Zilizoshinda',
    home_chefs: 'Mapishi Bora',
    about_title: 'Hadithi Yetu',
    about_subtitle: 'Urithi wa Ubora wa Upishi',
    about_desc_1: 'Ilianzishwa kwa shauku ya vyakula vya ajabu, Kolay Restaurant imekuwa nguzo ya chakula bora tangu mwanzoni mwake.',
    about_desc_2: 'Wapishi wetu wanapata viungo bora kutoka duniani kote, wakichanganya mbinu za jadi na uvumbuzi wa kisasa.',
    about_award: 'Mkahawa wa Nyota ya Michelin',
    about_commitment: 'Ahadi Yetu',
    about_commitment_desc: 'Tunaamini kila mlo unapaswa kuwa uzoefu. Kutoka viungo vipya vya shamba hadi upangaji mzuri, ubora ndio kiwango chetu.',
    menu_title: 'Menyu Yetu',
    menu_subtitle: 'Kazi za Upishi',
    menu_explore: 'Angalia Menyu Kamili',
    menu_order_online: 'Agiza Mtandaoni',
    gallery_title: 'Picha',
    gallery_subtitle: 'Karamu ya Macho',
    reservations_title: 'Mapaji',
    reservations_subtitle: 'Hifadhi Meza Yako',
    reservation_name: 'Jina Kamili',
    reservation_email: 'Anwani ya Barua Pepe',
    reservation_phone: 'Nambari ya Simu',
    reservation_date: 'Tarehe',
    reservation_time: 'Wakati',
    reservation_guests: 'Idadi ya Wageni',
    reservation_notes: 'Maombi Maalum',
    reservation_submit: 'Hifadhi Meza',
    reservation_success: 'Uhifadhi umethibitishwa!',
    reservation_select_guests: 'Chagua wageni',
    login_title: 'Karibu Tena',
    login_subtitle: 'Ingia kwenye akaunti yako',
    login_email: 'Barua Pepe',
    login_password: 'Nenosiri',
    login_btn: 'Ingia',
    login_no_account: 'Huna akaunti?',
    login_register: 'Fungua moja',
    register_title: 'Fungua Akaunti',
    register_subtitle: 'Jiunge na Kolay Restaurant',
    register_username: 'Jina la Mtumiaji',
    register_email: 'Barua Pepe',
    register_password: 'Nenosiri',
    register_confirm: 'Thibitisha Nenosiri',
    register_btn: 'Fungua Akaunti',
    register_have_account: 'Una akaunti tayari?',
    register_sign_in: 'Ingia',
    dashboard_title: 'Dashibodi',
    dashboard_total_orders: 'Maagizo Yote',
    dashboard_revenue: 'Mapato',
    dashboard_customers: 'Wateja',
    dashboard_avg_order: 'Agizo la Wastani',
    dashboard_recent_orders: 'Maagizo ya Hivi Karibuni',
    dashboard_low_stock: 'Vitu vya Hifadhi Ndogo',
    pos_title: 'Mfumo wa Mauzo',
    pos_search: 'Tafuta vitu...',
    pos_order_summary: 'Muhtasari wa Agizo',
    pos_total: 'Jumla',
    pos_place_order: 'Weka Agizo',
    pos_clear: 'Futa',
    pos_categories: 'Kategoria',
    kds_title: 'Onyesho la Jiko',
    kds_new: 'Mpya',
    kds_preparing: 'Inaandaliwa',
    kds_ready: 'Tayari',
    kds_mark_ready: 'Weka Tayari',
    inventory_title: 'Hifadhi',
    inventory_add_item: 'Ongeza Kitu',
    inventory_search: 'Tafuta hifadhi...',
    inventory_item_name: 'Jina la Kitu',
    inventory_quantity: 'Idadi',
    inventory_unit: 'Kitengo',
    inventory_low_stock: 'Hifadhi Ndogo',
    bookings_title: 'Miadi Yangu',
    bookings_upcoming: 'Ijayo',
    bookings_past: 'Iliyopita',
    bookings_cancel: 'Ghairi',
    bookings_no_bookings: 'Hakuna miadi iliyopatikana',
    careers_title: 'Kazi',
    careers_subtitle: 'Jiunge na Timu Yetu',
    careers_apply: 'Omba Sasa',
    careers_no_positions: 'Hakuna nafasi wazi kwa sasa.',
    loading: 'Inapakia...',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    search: 'Tafuta',
    add: 'Ongeza',
    update: 'Sasisha',
    confirm: 'Thibitisha',
    back: 'Rudi',
    next: 'Mbele',
    close: 'Funga',
    yes: 'Ndiyo',
    no: 'Hapana',
  },

  zh: {
    nav_about: '关于我们',
    nav_menu: '菜单',
    nav_reservations: '预订',
    nav_gallery: '图库',
    nav_contact: '联系我们',
    nav_careers: '招聘',
    nav_home: '首页',
    nav_order: '点餐',
    nav_offers: '优惠',
    nav_sign_in: '登录',
    nav_create_account: '创建账户',
    nav_my_bookings: '我的预订',
    nav_rate_us: '评价我们',
    nav_client_view: '客户视图',
    nav_dashboard: '仪表板',
    nav_kds: '厨房显示',
    nav_inventory: '库存',
    nav_bookings: '预订管理',
    nav_specialties: '特色菜',
    nav_orders: '订单',
    nav_employees: '员工',
    nav_admin_console: '管理控制台',
    nav_sign_out: '退出登录',
    nav_reset_system: '重置系统',
    portal_admin: '管理员门户',
    portal_staff: '员工门户',
    footer_navigate: '导航',
    footer_hours: '营业时间',
    footer_newsletter: '订阅',
    footer_newsletter_desc: '获取独家优惠和活动邀请。',
    footer_email_placeholder: '电子邮件地址',
    footer_join: '订阅',
    footer_copyright: '© 2026 Kolay餐厅。保留所有权利。',
    footer_privacy: '隐私政策',
    footer_terms: '使用条款',
    footer_staff_portal: '员工门户',
    footer_language: '语言',
    footer_every_day: '每天',
    footer_open_247: '24小时营业',
    footer_tagline: '为欣赏生活精致之处的人打造的精湛烹饪体验。',
    home_hero_subtitle: '非凡的烹饪之旅',
    home_hero_title_1: '每道菜肴',
    home_hero_title_2: '都讲述一个故事',
    home_hero_desc: '体验风味、氛围与服务的完美和谐。我们创造永久的美好记忆。',
    home_reserve_table: '预订餐桌',
    home_explore_menu: '浏览菜单',
    home_guests_served: '服务客人数',
    home_years_excellence: '卓越年数',
    home_awards_won: '获奖数量',
    home_chefs: '主厨',
    about_title: '我们的故事',
    about_subtitle: '烹饪卓越的传承',
    about_desc_1: 'Kolay餐厅秉持对非凡美食的热情而创立，自成立以来一直是精致餐饮的基石。',
    about_desc_2: '我们的厨师从全球采购最优质的食材，将传统技艺与现代创新融合，创造难忘的用餐体验。',
    about_award: '米其林星级餐厅',
    about_commitment: '我们的承诺',
    about_commitment_desc: '我们相信每一顿饭都应该是一次体验。从新鲜农场食材到精心摆盘，卓越是我们的承诺。',
    menu_title: '我们的菜单',
    menu_subtitle: '烹饪杰作',
    menu_explore: '浏览完整菜单',
    menu_order_online: '在线点餐',
    gallery_title: '图库',
    gallery_subtitle: '视觉盛宴',
    reservations_title: '预订',
    reservations_subtitle: '预订您的餐桌',
    reservation_name: '全名',
    reservation_email: '电子邮件地址',
    reservation_phone: '电话号码',
    reservation_date: '日期',
    reservation_time: '时间',
    reservation_guests: '就餐人数',
    reservation_notes: '特殊要求',
    reservation_submit: '预订餐桌',
    reservation_success: '预订已确认！',
    reservation_select_guests: '选择人数',
    login_title: '欢迎回来',
    login_subtitle: '登录您的账户',
    login_email: '邮箱',
    login_password: '密码',
    login_btn: '登录',
    login_no_account: '没有账户？',
    login_register: '创建一个',
    register_title: '创建账户',
    register_subtitle: '加入Kolay餐厅',
    register_username: '用户名',
    register_email: '邮箱',
    register_password: '密码',
    register_confirm: '确认密码',
    register_btn: '创建账户',
    register_have_account: '已有账户？',
    register_sign_in: '登录',
    dashboard_title: '仪表板',
    dashboard_total_orders: '总订单',
    dashboard_revenue: '收入',
    dashboard_customers: '客户',
    dashboard_avg_order: '平均订单',
    dashboard_recent_orders: '最近订单',
    dashboard_low_stock: '库存不足',
    pos_title: '销售点',
    pos_search: '搜索商品...',
    pos_order_summary: '订单摘要',
    pos_total: '总计',
    pos_place_order: '下单',
    pos_clear: '清空',
    pos_categories: '分类',
    kds_title: '厨房显示系统',
    kds_new: '新订单',
    kds_preparing: '准备中',
    kds_ready: '已完成',
    kds_mark_ready: '标记完成',
    inventory_title: '库存',
    inventory_add_item: '添加商品',
    inventory_search: '搜索库存...',
    inventory_item_name: '商品名称',
    inventory_quantity: '数量',
    inventory_unit: '单位',
    inventory_low_stock: '库存不足',
    bookings_title: '我的预订',
    bookings_upcoming: '即将到来',
    bookings_past: '过去',
    bookings_cancel: '取消',
    bookings_no_bookings: '未找到预订',
    careers_title: '招聘',
    careers_subtitle: '加入我们的团队',
    careers_apply: '立即申请',
    careers_no_positions: '目前没有空缺职位。',
    loading: '加载中...',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    search: '搜索',
    add: '添加',
    update: '更新',
    confirm: '确认',
    back: '返回',
    next: '下一步',
    close: '关闭',
    yes: '是',
    no: '否',
  },

  hi: {
    nav_about: 'हमारे बारे में',
    nav_menu: 'मेनू',
    nav_reservations: 'आरक्षण',
    nav_gallery: 'गैलरी',
    nav_contact: 'संपर्क',
    nav_careers: 'करियर',
    nav_home: 'होम',
    nav_order: 'ऑर्डर',
    nav_offers: 'ऑफर',
    nav_sign_in: 'साइन इन',
    nav_create_account: 'खाता बनाएं',
    nav_my_bookings: 'मेरी बुकिंग',
    nav_rate_us: 'हमें रेट करें',
    nav_client_view: 'क्लाइंट व्यू',
    nav_dashboard: 'डैशबोर्ड',
    nav_kds: 'KDS',
    nav_inventory: 'इन्वेंटरी',
    nav_bookings: 'बुकिंग',
    nav_specialties: 'विशेषताएं',
    nav_orders: 'ऑर्डर',
    nav_employees: 'कर्मचारी',
    nav_admin_console: 'एडमिन कंसोल',
    nav_sign_out: 'साइन आउट',
    nav_reset_system: 'सिस्टम रीसेट',
    portal_admin: 'एडमिन पोर्टल',
    portal_staff: 'स्टाफ पोर्टल',
    footer_navigate: 'नेविगेट',
    footer_hours: 'समय',
    footer_newsletter: 'न्यूज़लेटर',
    footer_newsletter_desc: 'विशेष ऑफर और इवेंट आमंत्रण पाएं।',
    footer_email_placeholder: 'ईमेल पता',
    footer_join: 'जुड़ें',
    footer_copyright: '© 2026 Kolay Restaurant. सर्वाधिकार सुरक्षित।',
    footer_privacy: 'गोपनीयता नीति',
    footer_terms: 'उपयोग की शर्तें',
    footer_staff_portal: 'स्टाफ पोर्टल',
    footer_language: 'भाषा',
    footer_every_day: 'हर दिन',
    footer_open_247: '24/7 खुला',
    footer_tagline: 'जीवन की बेहतरीन चीजों की सराहना करने वालों के लिए बनाए गए अद्भुत पाक अनुभव।',
    home_hero_subtitle: 'एक असाधारण पाक यात्रा',
    home_hero_title_1: 'जहाँ हर व्यंजन',
    home_hero_title_2: 'एक कहानी कहता है',
    home_hero_desc: 'स्वाद, माहौल और सेवा के सही सामंजस्य का अनुभव करें। हम जीवन भर याद रहने वाली यादें बनाते हैं।',
    home_reserve_table: 'टेबल बुक करें',
    home_explore_menu: 'मेनू देखें',
    home_guests_served: 'अतिथि सेवित',
    home_years_excellence: 'उत्कृष्टता के वर्ष',
    home_awards_won: 'पुरस्कार जीते',
    home_chefs: 'मास्टर शेफ',
    about_title: 'हमारी कहानी',
    about_subtitle: 'पाक उत्कृष्टता की विरासत',
    about_desc_1: 'असाधारण व्यंजनों के प्रति जुनून के साथ स्थापित, Kolay Restaurant अपनी स्थापना के बाद से बेहतरीन डाइनिंग की आधारशिला रही है।',
    about_desc_2: 'हमारे शेफ वैश्विक स्तर पर सर्वोत्तम सामग्री प्राप्त करते हैं, पारंपरिक तकनीकों को आधुनिक नवाचार के साथ मिलाकर अविस्मरणीय भोजन अनुभव बनाते हैं।',
    about_award: 'मिशेलिन स्टार रेस्तरां',
    about_commitment: 'हमारी प्रतिबद्धता',
    about_commitment_desc: 'हम मानते हैं कि हर भोजन एक अनुभव होना चाहिए। फार्म-ताजी सामग्री से लेकर सावधानीपूर्वक प्लेटिंग तक, उत्कृष्टता हमारा वादा है।',
    menu_title: 'हमारा मेनू',
    menu_subtitle: 'पाक कृतियां',
    menu_explore: 'पूरा मेनू देखें',
    menu_order_online: 'ऑनलाइन ऑर्डर करें',
    gallery_title: 'गैलरी',
    gallery_subtitle: 'दृश्य उत्सव',
    reservations_title: 'आरक्षण',
    reservations_subtitle: 'अपनी टेबल बुक करें',
    reservation_name: 'पूरा नाम',
    reservation_email: 'ईमेल पता',
    reservation_phone: 'फोन नंबर',
    reservation_date: 'तारीख',
    reservation_time: 'समय',
    reservation_guests: 'अतिथियों की संख्या',
    reservation_notes: 'विशेष अनुरोध',
    reservation_submit: 'टेबल बुक करें',
    reservation_success: 'आरक्षण की पुष्टि हो गई!',
    reservation_select_guests: 'अतिथि चुनें',
    login_title: 'वापस स्वागत है',
    login_subtitle: 'अपने खाते में साइन इन करें',
    login_email: 'ईमेल',
    login_password: 'पासवर्ड',
    login_btn: 'साइन इन',
    login_no_account: 'खाता नहीं है?',
    login_register: 'बनाएं',
    register_title: 'खाता बनाएं',
    register_subtitle: 'Kolay Restaurant में शामिल हों',
    register_username: 'उपयोगकर्ता नाम',
    register_email: 'ईमेल',
    register_password: 'पासवर्ड',
    register_confirm: 'पासवर्ड की पुष्टि करें',
    register_btn: 'खाता बनाएं',
    register_have_account: 'पहले से खाता है?',
    register_sign_in: 'साइन इन',
    dashboard_title: 'डैशबोर्ड',
    dashboard_total_orders: 'कुल ऑर्डर',
    dashboard_revenue: 'राजस्व',
    dashboard_customers: 'ग्राहक',
    dashboard_avg_order: 'औसत ऑर्डर',
    dashboard_recent_orders: 'हाल के ऑर्डर',
    dashboard_low_stock: 'कम स्टॉक',
    pos_title: 'पॉइंट ऑफ सेल',
    pos_search: 'आइटम खोजें...',
    pos_order_summary: 'ऑर्डर सारांश',
    pos_total: 'कुल',
    pos_place_order: 'ऑर्डर दें',
    pos_clear: 'साफ करें',
    pos_categories: 'श्रेणियां',
    kds_title: 'किचन डिस्प्ले',
    kds_new: 'नया',
    kds_preparing: 'तैयार हो रहा है',
    kds_ready: 'तैयार',
    kds_mark_ready: 'तैयार मार्क करें',
    inventory_title: 'इन्वेंटरी',
    inventory_add_item: 'आइटम जोड़ें',
    inventory_search: 'इन्वेंटरी खोजें...',
    inventory_item_name: 'आइटम का नाम',
    inventory_quantity: 'मात्रा',
    inventory_unit: 'इकाई',
    inventory_low_stock: 'कम स्टॉक',
    bookings_title: 'मेरी बुकिंग',
    bookings_upcoming: 'आगामी',
    bookings_past: 'पिछले',
    bookings_cancel: 'रद्द करें',
    bookings_no_bookings: 'कोई बुकिंग नहीं मिली',
    careers_title: 'करियर',
    careers_subtitle: 'हमारी टीम में शामिल हों',
    careers_apply: 'अभी आवेदन करें',
    careers_no_positions: 'इस समय कोई रिक्त पद नहीं।',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    search: 'खोजें',
    add: 'जोड़ें',
    update: 'अपडेट करें',
    confirm: 'पुष्टि करें',
    back: 'वापस',
    next: 'अगला',
    close: 'बंद करें',
    yes: 'हाँ',
    no: 'नहीं',
  },

  es: {
    nav_about: 'Acerca de',
    nav_menu: 'Menú',
    nav_reservations: 'Reservaciones',
    nav_gallery: 'Galería',
    nav_contact: 'Contacto',
    nav_careers: 'Empleos',
    nav_home: 'Inicio',
    nav_order: 'Pedir',
    nav_offers: 'Ofertas',
    nav_sign_in: 'Iniciar sesión',
    nav_create_account: 'Crear cuenta',
    nav_my_bookings: 'Mis reservas',
    nav_rate_us: 'Califícanos',
    nav_client_view: 'Vista del cliente',
    nav_dashboard: 'Panel',
    nav_kds: 'KDS',
    nav_inventory: 'Inventario',
    nav_bookings: 'Reservas',
    nav_specialties: 'Especialidades',
    nav_orders: 'Pedidos',
    nav_employees: 'Empleados',
    nav_admin_console: 'Consola de admin',
    nav_sign_out: 'Cerrar sesión',
    nav_reset_system: 'Restablecer sistema',
    portal_admin: 'Portal de administrador',
    portal_staff: 'Portal de personal',
    footer_navigate: 'Navegar',
    footer_hours: 'Horario',
    footer_newsletter: 'Boletín',
    footer_newsletter_desc: 'Recibe ofertas exclusivas e invitaciones a eventos.',
    footer_email_placeholder: 'Dirección de correo',
    footer_join: 'Unirse',
    footer_copyright: '© 2026 Kolay Restaurant. Todos los derechos reservados.',
    footer_privacy: 'Política de privacidad',
    footer_terms: 'Términos de uso',
    footer_staff_portal: 'Portal de personal',
    footer_language: 'Idioma',
    footer_every_day: 'Todos los días',
    footer_open_247: 'Abierto 24/7',
    footer_tagline: 'Experiencias culinarias artesanales para quienes aprecian lo mejor de la vida.',
    home_hero_subtitle: 'Un Viaje Culinario Extraordinario',
    home_hero_title_1: 'Donde Cada Plato',
    home_hero_title_2: 'Cuenta una Historia',
    home_hero_desc: 'Experimenta la perfecta armonía de sabores, ambiente y servicio. Creamos recuerdos que duran toda la vida.',
    home_reserve_table: 'Reservar Mesa',
    home_explore_menu: 'Explorar Menú',
    home_guests_served: 'Huéspedes Atendidos',
    home_years_excellence: 'Años de Excelencia',
    home_awards_won: 'Premios Ganados',
    home_chefs: 'Chefs Maestros',
    about_title: 'Nuestra Historia',
    about_subtitle: 'Un Legado de Excelencia Culinaria',
    about_desc_1: 'Fundado con pasión por la cocina extraordinaria, Kolay Restaurant ha sido un pilar de la alta cocina desde sus inicios.',
    about_desc_2: 'Nuestros chefs buscan los mejores ingredientes a nivel mundial, combinando técnicas tradicionales con innovación moderna.',
    about_award: 'Restaurante Estrella Michelin',
    about_commitment: 'Nuestro Compromiso',
    about_commitment_desc: 'Creemos que cada comida debe ser una experiencia. Desde ingredientes frescos hasta el emplatado meticuloso, la excelencia es nuestra promesa.',
    menu_title: 'Nuestro Menú',
    menu_subtitle: 'Obras Maestras Culinarias',
    menu_explore: 'Ver Menú Completo',
    menu_order_online: 'Pedir en Línea',
    gallery_title: 'Galería',
    gallery_subtitle: 'Un Festín Visual',
    reservations_title: 'Reservaciones',
    reservations_subtitle: 'Reserva Tu Mesa',
    reservation_name: 'Nombre completo',
    reservation_email: 'Correo electrónico',
    reservation_phone: 'Teléfono',
    reservation_date: 'Fecha',
    reservation_time: 'Hora',
    reservation_guests: 'Número de personas',
    reservation_notes: 'Solicitudes especiales',
    reservation_submit: 'Reservar Mesa',
    reservation_success: '¡Reserva confirmada!',
    reservation_select_guests: 'Seleccionar personas',
    login_title: 'Bienvenido de vuelta',
    login_subtitle: 'Inicia sesión en tu cuenta',
    login_email: 'Correo',
    login_password: 'Contraseña',
    login_btn: 'Iniciar sesión',
    login_no_account: '¿No tienes cuenta?',
    login_register: 'Créala',
    register_title: 'Crear Cuenta',
    register_subtitle: 'Únete a Kolay Restaurant',
    register_username: 'Usuario',
    register_email: 'Correo',
    register_password: 'Contraseña',
    register_confirm: 'Confirmar contraseña',
    register_btn: 'Crear Cuenta',
    register_have_account: '¿Ya tienes cuenta?',
    register_sign_in: 'Iniciar sesión',
    dashboard_title: 'Panel',
    dashboard_total_orders: 'Total pedidos',
    dashboard_revenue: 'Ingresos',
    dashboard_customers: 'Clientes',
    dashboard_avg_order: 'Pedido promedio',
    dashboard_recent_orders: 'Pedidos recientes',
    dashboard_low_stock: 'Stock bajo',
    pos_title: 'Punto de Venta',
    pos_search: 'Buscar artículos...',
    pos_order_summary: 'Resumen del pedido',
    pos_total: 'Total',
    pos_place_order: 'Realizar pedido',
    pos_clear: 'Limpiar',
    pos_categories: 'Categorías',
    kds_title: 'Pantalla de Cocina',
    kds_new: 'Nuevo',
    kds_preparing: 'Preparando',
    kds_ready: 'Listo',
    kds_mark_ready: 'Marcar como listo',
    inventory_title: 'Inventario',
    inventory_add_item: 'Agregar artículo',
    inventory_search: 'Buscar inventario...',
    inventory_item_name: 'Nombre del artículo',
    inventory_quantity: 'Cantidad',
    inventory_unit: 'Unidad',
    inventory_low_stock: 'Stock bajo',
    bookings_title: 'Mis Reservas',
    bookings_upcoming: 'Próximas',
    bookings_past: 'Pasadas',
    bookings_cancel: 'Cancelar',
    bookings_no_bookings: 'No se encontraron reservas',
    careers_title: 'Empleos',
    careers_subtitle: 'Únete a Nuestro Equipo',
    careers_apply: 'Aplicar ahora',
    careers_no_positions: 'No hay posiciones disponibles por el momento.',
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    search: 'Buscar',
    add: 'Agregar',
    update: 'Actualizar',
    confirm: 'Confirmar',
    back: 'Atrás',
    next: 'Siguiente',
    close: 'Cerrar',
    yes: 'Sí',
    no: 'No',
  },

  ar: {
    nav_about: 'من نحن',
    nav_menu: 'القائمة',
    nav_reservations: 'الحجوزات',
    nav_gallery: 'المعرض',
    nav_contact: 'تواصل معنا',
    nav_careers: 'الوظائف',
    nav_home: 'الرئيسية',
    nav_order: 'اطلب',
    nav_offers: 'العروض',
    nav_sign_in: 'تسجيل الدخول',
    nav_create_account: 'إنشاء حساب',
    nav_my_bookings: 'حجوزاتي',
    nav_rate_us: 'قيّمنا',
    nav_client_view: 'عرض العميل',
    nav_dashboard: 'لوحة التحكم',
    nav_kds: 'شاشة المطبخ',
    nav_inventory: 'المخزون',
    nav_bookings: 'الحجوزات',
    nav_specialties: 'التخصصات',
    nav_orders: 'الطلبات',
    nav_employees: 'الموظفون',
    nav_admin_console: 'لوحة الإدارة',
    nav_sign_out: 'تسجيل الخروج',
    nav_reset_system: 'إعادة تعيين النظام',
    portal_admin: 'بوابة المسؤول',
    portal_staff: 'بوابة الموظفين',
    footer_navigate: 'التنقل',
    footer_hours: 'أوقات العمل',
    footer_newsletter: 'النشرة الإخبارية',
    footer_newsletter_desc: 'احصل على عروض حصرية ودعوات للفعاليات.',
    footer_email_placeholder: 'عنوان البريد الإلكتروني',
    footer_join: 'انضم',
    footer_copyright: '© 2026 مطعم كولاي. جميع الحقوق محفوظة.',
    footer_privacy: 'سياسة الخصوصية',
    footer_terms: 'شروط الاستخدام',
    footer_staff_portal: 'بوابة الموظفين',
    footer_language: 'اللغة',
    footer_every_day: 'كل يوم',
    footer_open_247: 'مفتوح 24/7',
    footer_tagline: 'تجارب طهي حرفية مصممة لمن يقدرون أرقى ما في الحياة.',
    home_hero_subtitle: 'رحلة طهي استثنائية',
    home_hero_title_1: 'حيث كل طبق',
    home_hero_title_2: 'يحكي قصة',
    home_hero_desc: 'اختبر التناغم المثالي بين النكهات والأجواء والخدمة. نحن نصنع ذكريات تدوم مدى الحياة.',
    home_reserve_table: 'احجز طاولة',
    home_explore_menu: 'استكشف القائمة',
    home_guests_served: 'الضيوف المخدومون',
    home_years_excellence: 'سنوات من التميز',
    home_awards_won: 'الجوائز المكتسبة',
    home_chefs: 'الطهاة المتميزون',
    about_title: 'قصتنا',
    about_subtitle: 'إرث من التميز الطهوي',
    about_desc_1: 'تأسس مطعم كولاي بشغف للمأكولات الاستثنائية، وقد كان ركيزة للطعام الفاخر منذ نشأته.',
    about_desc_2: 'يحصل طهاتنا على أجود المكونات من جميع أنحاء العالم، مزجاً بين التقنيات التقليدية والابتكار الحديث.',
    about_award: 'مطعم نجمة ميشلان',
    about_commitment: 'التزامنا',
    about_commitment_desc: 'نؤمن بأن كل وجبة يجب أن تكون تجربة. من المكونات الطازجة إلى التقديم الدقيق، التميز هو وعدنا.',
    menu_title: 'قائمتنا',
    menu_subtitle: 'روائع طهوية',
    menu_explore: 'استكشف القائمة الكاملة',
    menu_order_online: 'اطلب عبر الإنترنت',
    gallery_title: 'المعرض',
    gallery_subtitle: 'وليمة بصرية',
    reservations_title: 'الحجوزات',
    reservations_subtitle: 'احجز طاولتك',
    reservation_name: 'الاسم الكامل',
    reservation_email: 'عنوان البريد الإلكتروني',
    reservation_phone: 'رقم الهاتف',
    reservation_date: 'التاريخ',
    reservation_time: 'الوقت',
    reservation_guests: 'عدد الضيوف',
    reservation_notes: 'طلبات خاصة',
    reservation_submit: 'احجز الطاولة',
    reservation_success: 'تم تأكيد الحجز!',
    reservation_select_guests: 'اختر الضيوف',
    login_title: 'مرحباً بعودتك',
    login_subtitle: 'سجل الدخول إلى حسابك',
    login_email: 'البريد الإلكتروني',
    login_password: 'كلمة المرور',
    login_btn: 'تسجيل الدخول',
    login_no_account: 'ليس لديك حساب؟',
    login_register: 'أنشئ واحداً',
    register_title: 'إنشاء حساب',
    register_subtitle: 'انضم إلى مطعم كولاي',
    register_username: 'اسم المستخدم',
    register_email: 'البريد الإلكتروني',
    register_password: 'كلمة المرور',
    register_confirm: 'تأكيد كلمة المرور',
    register_btn: 'إنشاء حساب',
    register_have_account: 'لديك حساب بالفعل؟',
    register_sign_in: 'تسجيل الدخول',
    dashboard_title: 'لوحة التحكم',
    dashboard_total_orders: 'إجمالي الطلبات',
    dashboard_revenue: 'الإيرادات',
    dashboard_customers: 'العملاء',
    dashboard_avg_order: 'متوسط الطلب',
    dashboard_recent_orders: 'الطلبات الأخيرة',
    dashboard_low_stock: 'مخزون منخفض',
    pos_title: 'نقطة البيع',
    pos_search: 'ابحث عن عناصر...',
    pos_order_summary: 'ملخص الطلب',
    pos_total: 'المجموع',
    pos_place_order: 'تقديم الطلب',
    pos_clear: 'مسح',
    pos_categories: 'الفئات',
    kds_title: 'شاشة المطبخ',
    kds_new: 'جديد',
    kds_preparing: 'قيد التحضير',
    kds_ready: 'جاهز',
    kds_mark_ready: 'تحديد جاهز',
    inventory_title: 'المخزون',
    inventory_add_item: 'إضافة عنصر',
    inventory_search: 'البحث في المخزون...',
    inventory_item_name: 'اسم العنصر',
    inventory_quantity: 'الكمية',
    inventory_unit: 'الوحدة',
    inventory_low_stock: 'مخزون منخفض',
    bookings_title: 'حجوزاتي',
    bookings_upcoming: 'القادمة',
    bookings_past: 'الماضية',
    bookings_cancel: 'إلغاء',
    bookings_no_bookings: 'لا توجد حجوزات',
    careers_title: 'الوظائف',
    careers_subtitle: 'انضم إلى فريقنا',
    careers_apply: 'تقدم الآن',
    careers_no_positions: 'لا توجد وظائف شاغرة في الوقت الحالي.',
    loading: 'جار التحميل...',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    search: 'بحث',
    add: 'إضافة',
    update: 'تحديث',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    close: 'إغلاق',
    yes: 'نعم',
    no: 'لا',
  },

  fr: {
    nav_about: 'À propos',
    nav_menu: 'Menu',
    nav_reservations: 'Réservations',
    nav_gallery: 'Galerie',
    nav_contact: 'Contact',
    nav_careers: 'Carrières',
    nav_home: 'Accueil',
    nav_order: 'Commander',
    nav_offers: 'Offres',
    nav_sign_in: 'Se connecter',
    nav_create_account: 'Créer un compte',
    nav_my_bookings: 'Mes réservations',
    nav_rate_us: 'Nous noter',
    nav_client_view: 'Vue client',
    nav_dashboard: 'Tableau de bord',
    nav_kds: 'KDS',
    nav_inventory: 'Inventaire',
    nav_bookings: 'Réservations',
    nav_specialties: 'Spécialités',
    nav_orders: 'Commandes',
    nav_employees: 'Employés',
    nav_admin_console: 'Console admin',
    nav_sign_out: 'Se déconnecter',
    nav_reset_system: 'Réinitialiser',
    portal_admin: 'Portail administrateur',
    portal_staff: 'Portail du personnel',
    footer_navigate: 'Navigation',
    footer_hours: 'Horaires',
    footer_newsletter: 'Newsletter',
    footer_newsletter_desc: 'Recevez des offres exclusives et des invitations à nos événements.',
    footer_email_placeholder: 'Adresse email',
    footer_join: 'Rejoindre',
    footer_copyright: '© 2026 Kolay Restaurant. Tous droits réservés.',
    footer_privacy: 'Politique de confidentialité',
    footer_terms: "Conditions d'utilisation",
    footer_staff_portal: 'Portail du personnel',
    footer_language: 'Langue',
    footer_every_day: 'Tous les jours',
    footer_open_247: 'Ouvert 24h/24',
    footer_tagline: "Des expériences culinaires artisanales créées pour ceux qui apprécient les meilleures choses de la vie.",
    home_hero_subtitle: 'Un Voyage Culinaire Extraordinaire',
    home_hero_title_1: 'Où Chaque Plat',
    home_hero_title_2: 'Raconte une Histoire',
    home_hero_desc: "Vivez l'harmonie parfaite des saveurs, de l'ambiance et du service. Nous créons des souvenirs qui durent toute une vie.",
    home_reserve_table: 'Réserver une table',
    home_explore_menu: 'Explorer le menu',
    home_guests_served: 'Clients servis',
    home_years_excellence: "Années d'excellence",
    home_awards_won: 'Prix remportés',
    home_chefs: 'Chefs maîtres',
    about_title: 'Notre histoire',
    about_subtitle: "Un héritage d'excellence culinaire",
    about_desc_1: "Fondé avec passion pour la cuisine extraordinaire, Kolay Restaurant est une référence de la gastronomie depuis ses débuts.",
    about_desc_2: "Nos chefs sélectionnent les meilleurs ingrédients du monde entier, alliant techniques traditionnelles et innovation moderne.",
    about_award: 'Restaurant étoilé Michelin',
    about_commitment: 'Notre engagement',
    about_commitment_desc: "Nous croyons que chaque repas doit être une expérience. Des ingrédients frais à la présentation soignée, l'excellence est notre promesse.",
    menu_title: 'Notre menu',
    menu_subtitle: 'Chefs-d\'œuvre culinaires',
    menu_explore: 'Voir le menu complet',
    menu_order_online: 'Commander en ligne',
    gallery_title: 'Galerie',
    gallery_subtitle: 'Un festin visuel',
    reservations_title: 'Réservations',
    reservations_subtitle: 'Réservez votre table',
    reservation_name: 'Nom complet',
    reservation_email: 'Adresse email',
    reservation_phone: 'Numéro de téléphone',
    reservation_date: 'Date',
    reservation_time: 'Heure',
    reservation_guests: 'Nombre de personnes',
    reservation_notes: 'Demandes spéciales',
    reservation_submit: 'Réserver la table',
    reservation_success: 'Réservation confirmée !',
    reservation_select_guests: 'Sélectionner le nombre',
    login_title: 'Bon retour',
    login_subtitle: 'Connectez-vous à votre compte',
    login_email: 'Email',
    login_password: 'Mot de passe',
    login_btn: 'Se connecter',
    login_no_account: 'Pas encore de compte ?',
    login_register: "Créez-en un",
    register_title: 'Créer un compte',
    register_subtitle: 'Rejoignez Kolay Restaurant',
    register_username: "Nom d'utilisateur",
    register_email: 'Email',
    register_password: 'Mot de passe',
    register_confirm: 'Confirmer le mot de passe',
    register_btn: 'Créer un compte',
    register_have_account: 'Vous avez déjà un compte ?',
    register_sign_in: 'Se connecter',
    dashboard_title: 'Tableau de bord',
    dashboard_total_orders: 'Total commandes',
    dashboard_revenue: 'Revenus',
    dashboard_customers: 'Clients',
    dashboard_avg_order: 'Commande moyenne',
    dashboard_recent_orders: 'Commandes récentes',
    dashboard_low_stock: 'Stock bas',
    pos_title: 'Point de vente',
    pos_search: 'Rechercher...',
    pos_order_summary: 'Récapitulatif',
    pos_total: 'Total',
    pos_place_order: 'Passer la commande',
    pos_clear: 'Vider',
    pos_categories: 'Catégories',
    kds_title: "Affichage cuisine",
    kds_new: 'Nouveau',
    kds_preparing: 'En préparation',
    kds_ready: 'Prêt',
    kds_mark_ready: 'Marquer prêt',
    inventory_title: 'Inventaire',
    inventory_add_item: 'Ajouter un article',
    inventory_search: "Rechercher l'inventaire...",
    inventory_item_name: "Nom de l'article",
    inventory_quantity: 'Quantité',
    inventory_unit: 'Unité',
    inventory_low_stock: 'Stock bas',
    bookings_title: 'Mes réservations',
    bookings_upcoming: 'À venir',
    bookings_past: 'Passées',
    bookings_cancel: 'Annuler',
    bookings_no_bookings: 'Aucune réservation trouvée',
    careers_title: 'Carrières',
    careers_subtitle: 'Rejoignez notre équipe',
    careers_apply: 'Postuler maintenant',
    careers_no_positions: 'Aucun poste disponible pour le moment.',
    loading: 'Chargement...',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    search: 'Rechercher',
    add: 'Ajouter',
    update: 'Mettre à jour',
    confirm: 'Confirmer',
    back: 'Retour',
    next: 'Suivant',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',
  },

  bn: {
    nav_about: 'আমাদের সম্পর্কে',
    nav_menu: 'মেনু',
    nav_reservations: 'সংরক্ষণ',
    nav_gallery: 'গ্যালারি',
    nav_contact: 'যোগাযোগ',
    nav_careers: 'ক্যারিয়ার',
    nav_home: 'হোম',
    nav_order: 'অর্ডার',
    nav_offers: 'অফার',
    nav_sign_in: 'সাইন ইন',
    nav_create_account: 'অ্যাকাউন্ট তৈরি করুন',
    nav_my_bookings: 'আমার বুকিং',
    nav_rate_us: 'আমাদের রেট করুন',
    nav_client_view: 'ক্লায়েন্ট ভিউ',
    nav_dashboard: 'ড্যাশবোর্ড',
    nav_kds: 'KDS',
    nav_inventory: 'ইনভেন্টরি',
    nav_bookings: 'বুকিং',
    nav_specialties: 'বিশেষত্ব',
    nav_orders: 'অর্ডার',
    nav_employees: 'কর্মচারী',
    nav_admin_console: 'অ্যাডমিন কনসোল',
    nav_sign_out: 'সাইন আউট',
    nav_reset_system: 'সিস্টেম রিসেট',
    portal_admin: 'অ্যাডমিন পোর্টাল',
    portal_staff: 'স্টাফ পোর্টাল',
    footer_navigate: 'নেভিগেট',
    footer_hours: 'সময়',
    footer_newsletter: 'নিউজলেটার',
    footer_newsletter_desc: 'একচেটিয়া অফার এবং ইভেন্ট আমন্ত্রণ পান।',
    footer_email_placeholder: 'ইমেইল ঠিকানা',
    footer_join: 'যোগ দিন',
    footer_copyright: '© 2026 Kolay Restaurant. সর্বস্বত্ব সংরক্ষিত।',
    footer_privacy: 'গোপনীয়তা নীতি',
    footer_terms: 'ব্যবহারের শর্তাবলী',
    footer_staff_portal: 'স্টাফ পোর্টাল',
    footer_language: 'ভাষা',
    footer_every_day: 'প্রতিদিন',
    footer_open_247: '24/7 খোলা',
    footer_tagline: 'যারা জীবনের সেরা জিনিসের কদর করেন তাদের জন্য তৈরি অসাধারণ রন্ধন অভিজ্ঞতা।',
    home_hero_subtitle: 'একটি অসাধারণ রন্ধন যাত্রা',
    home_hero_title_1: 'যেখানে প্রতিটি ডিশ',
    home_hero_title_2: 'একটি গল্প বলে',
    home_hero_desc: 'স্বাদ, পরিবেশ এবং সেবার নিখুঁত সামঞ্জস্য অনুভব করুন। আমরা জীবনব্যাপী স্মৃতি তৈরি করি।',
    home_reserve_table: 'টেবিল বুক করুন',
    home_explore_menu: 'মেনু দেখুন',
    home_guests_served: 'পরিবেশিত অতিথি',
    home_years_excellence: 'শ্রেষ্ঠত্বের বছর',
    home_awards_won: 'পুরস্কার জিতেছে',
    home_chefs: 'মাস্টার শেফ',
    about_title: 'আমাদের গল্প',
    about_subtitle: 'রন্ধন শ্রেষ্ঠত্বের উত্তরাধিকার',
    about_desc_1: 'অসাধারণ রন্ধনের প্রতি আবেগ নিয়ে প্রতিষ্ঠিত, Kolay Restaurant তার সূচনা থেকেই উন্নত ডাইনিং-এর ভিত্তিপ্রস্তর।',
    about_desc_2: 'আমাদের শেফরা বিশ্বব্যাপী সেরা উপকরণ সংগ্রহ করেন, ঐতিহ্যবাহী কৌশলের সাথে আধুনিক উদ্ভাবন মিশিয়ে অবিস্মরণীয় ডাইনিং অভিজ্ঞতা তৈরি করেন।',
    about_award: 'মিশেলিন স্টার রেস্তোরাঁ',
    about_commitment: 'আমাদের প্রতিশ্রুতি',
    about_commitment_desc: 'আমরা বিশ্বাস করি প্রতিটি খাবার একটি অভিজ্ঞতা হওয়া উচিত। তাজা উপকরণ থেকে সতর্কতামূলক পরিবেশনা পর্যন্ত, শ্রেষ্ঠত্ব আমাদের প্রতিশ্রুতি।',
    menu_title: 'আমাদের মেনু',
    menu_subtitle: 'রন্ধন মাস্টারপিস',
    menu_explore: 'সম্পূর্ণ মেনু দেখুন',
    menu_order_online: 'অনলাইনে অর্ডার করুন',
    gallery_title: 'গ্যালারি',
    gallery_subtitle: 'দৃশ্যমান ভোজ',
    reservations_title: 'সংরক্ষণ',
    reservations_subtitle: 'আপনার টেবিল সংরক্ষণ করুন',
    reservation_name: 'পূর্ণ নাম',
    reservation_email: 'ইমেইল ঠিকানা',
    reservation_phone: 'ফোন নম্বর',
    reservation_date: 'তারিখ',
    reservation_time: 'সময়',
    reservation_guests: 'অতিথির সংখ্যা',
    reservation_notes: 'বিশেষ অনুরোধ',
    reservation_submit: 'টেবিল বুক করুন',
    reservation_success: 'সংরক্ষণ নিশ্চিত!',
    reservation_select_guests: 'অতিথি বেছে নিন',
    login_title: 'আবার স্বাগতম',
    login_subtitle: 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
    login_email: 'ইমেইল',
    login_password: 'পাসওয়ার্ড',
    login_btn: 'সাইন ইন',
    login_no_account: 'অ্যাকাউন্ট নেই?',
    login_register: 'তৈরি করুন',
    register_title: 'অ্যাকাউন্ট তৈরি করুন',
    register_subtitle: 'Kolay Restaurant-এ যোগ দিন',
    register_username: 'ব্যবহারকারীর নাম',
    register_email: 'ইমেইল',
    register_password: 'পাসওয়ার্ড',
    register_confirm: 'পাসওয়ার্ড নিশ্চিত করুন',
    register_btn: 'অ্যাকাউন্ট তৈরি করুন',
    register_have_account: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    register_sign_in: 'সাইন ইন',
    dashboard_title: 'ড্যাশবোর্ড',
    dashboard_total_orders: 'মোট অর্ডার',
    dashboard_revenue: 'আয়',
    dashboard_customers: 'গ্রাহক',
    dashboard_avg_order: 'গড় অর্ডার',
    dashboard_recent_orders: 'সাম্প্রতিক অর্ডার',
    dashboard_low_stock: 'কম স্টক',
    pos_title: 'পয়েন্ট অব সেল',
    pos_search: 'আইটেম খুঁজুন...',
    pos_order_summary: 'অর্ডার সারসংক্ষেপ',
    pos_total: 'মোট',
    pos_place_order: 'অর্ডার দিন',
    pos_clear: 'পরিষ্কার করুন',
    pos_categories: 'বিভাগ',
    kds_title: 'কিচেন ডিসপ্লে',
    kds_new: 'নতুন',
    kds_preparing: 'প্রস্তুত হচ্ছে',
    kds_ready: 'প্রস্তুত',
    kds_mark_ready: 'প্রস্তুত চিহ্নিত করুন',
    inventory_title: 'ইনভেন্টরি',
    inventory_add_item: 'আইটেম যোগ করুন',
    inventory_search: 'ইনভেন্টরি খুঁজুন...',
    inventory_item_name: 'আইটেমের নাম',
    inventory_quantity: 'পরিমাণ',
    inventory_unit: 'একক',
    inventory_low_stock: 'কম স্টক',
    bookings_title: 'আমার বুকিং',
    bookings_upcoming: 'আসন্ন',
    bookings_past: 'অতীত',
    bookings_cancel: 'বাতিল করুন',
    bookings_no_bookings: 'কোনো বুকিং পাওয়া যায়নি',
    careers_title: 'ক্যারিয়ার',
    careers_subtitle: 'আমাদের দলে যোগ দিন',
    careers_apply: 'এখনই আবেদন করুন',
    careers_no_positions: 'এই মুহূর্তে কোনো শূন্য পদ নেই।',
    loading: 'লোড হচ্ছে...',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    search: 'খুঁজুন',
    add: 'যোগ করুন',
    update: 'আপডেট',
    confirm: 'নিশ্চিত করুন',
    back: 'পিছনে',
    next: 'পরবর্তী',
    close: 'বন্ধ করুন',
    yes: 'হ্যাঁ',
    no: 'না',
  },

  pt: {
    nav_about: 'Sobre',
    nav_menu: 'Cardápio',
    nav_reservations: 'Reservas',
    nav_gallery: 'Galeria',
    nav_contact: 'Contato',
    nav_careers: 'Carreiras',
    nav_home: 'Início',
    nav_order: 'Pedir',
    nav_offers: 'Ofertas',
    nav_sign_in: 'Entrar',
    nav_create_account: 'Criar conta',
    nav_my_bookings: 'Minhas reservas',
    nav_rate_us: 'Avaliar',
    nav_client_view: 'Visão do cliente',
    nav_dashboard: 'Painel',
    nav_kds: 'KDS',
    nav_inventory: 'Estoque',
    nav_bookings: 'Reservas',
    nav_specialties: 'Especialidades',
    nav_orders: 'Pedidos',
    nav_employees: 'Funcionários',
    nav_admin_console: 'Console admin',
    nav_sign_out: 'Sair',
    nav_reset_system: 'Reiniciar sistema',
    portal_admin: 'Portal do administrador',
    portal_staff: 'Portal da equipe',
    footer_navigate: 'Navegar',
    footer_hours: 'Horário',
    footer_newsletter: 'Newsletter',
    footer_newsletter_desc: 'Receba ofertas exclusivas e convites para eventos.',
    footer_email_placeholder: 'Endereço de email',
    footer_join: 'Inscrever',
    footer_copyright: '© 2026 Kolay Restaurant. Todos os direitos reservados.',
    footer_privacy: 'Política de privacidade',
    footer_terms: 'Termos de uso',
    footer_staff_portal: 'Portal da equipe',
    footer_language: 'Idioma',
    footer_every_day: 'Todos os dias',
    footer_open_247: 'Aberto 24/7',
    footer_tagline: 'Experiências culinárias artesanais criadas para quem aprecia as melhores coisas da vida.',
    home_hero_subtitle: 'Uma Jornada Culinária Extraordinária',
    home_hero_title_1: 'Onde Cada Prato',
    home_hero_title_2: 'Conta uma História',
    home_hero_desc: 'Experiencie a harmonia perfeita de sabores, ambiente e serviço. Criamos memórias que duram para sempre.',
    home_reserve_table: 'Reservar Mesa',
    home_explore_menu: 'Explorar Cardápio',
    home_guests_served: 'Clientes Atendidos',
    home_years_excellence: 'Anos de Excelência',
    home_awards_won: 'Prêmios Ganhos',
    home_chefs: 'Chefs Mestres',
    about_title: 'Nossa História',
    about_subtitle: 'Um Legado de Excelência Culinária',
    about_desc_1: 'Fundado com paixão pela culinária extraordinária, o Kolay Restaurant tem sido um pilar da alta gastronomia desde o início.',
    about_desc_2: 'Nossos chefs buscam os melhores ingredientes do mundo, combinando técnicas tradicionais com inovação moderna.',
    about_award: 'Restaurante Estrela Michelin',
    about_commitment: 'Nosso Compromisso',
    about_commitment_desc: 'Acreditamos que cada refeição deve ser uma experiência. Desde ingredientes frescos até a apresentação meticulosa, a excelência é nossa promessa.',
    menu_title: 'Nosso Cardápio',
    menu_subtitle: 'Obras-Primas Culinárias',
    menu_explore: 'Ver Cardápio Completo',
    menu_order_online: 'Pedir Online',
    gallery_title: 'Galeria',
    gallery_subtitle: 'Um Banquete Visual',
    reservations_title: 'Reservas',
    reservations_subtitle: 'Reserve Sua Mesa',
    reservation_name: 'Nome completo',
    reservation_email: 'Endereço de email',
    reservation_phone: 'Telefone',
    reservation_date: 'Data',
    reservation_time: 'Hora',
    reservation_guests: 'Número de pessoas',
    reservation_notes: 'Pedidos especiais',
    reservation_submit: 'Reservar Mesa',
    reservation_success: 'Reserva confirmada!',
    reservation_select_guests: 'Selecionar pessoas',
    login_title: 'Bem-vindo de volta',
    login_subtitle: 'Entre na sua conta',
    login_email: 'Email',
    login_password: 'Senha',
    login_btn: 'Entrar',
    login_no_account: 'Não tem conta?',
    login_register: 'Crie uma',
    register_title: 'Criar Conta',
    register_subtitle: 'Junte-se ao Kolay Restaurant',
    register_username: 'Usuário',
    register_email: 'Email',
    register_password: 'Senha',
    register_confirm: 'Confirmar senha',
    register_btn: 'Criar Conta',
    register_have_account: 'Já tem conta?',
    register_sign_in: 'Entrar',
    dashboard_title: 'Painel',
    dashboard_total_orders: 'Total de pedidos',
    dashboard_revenue: 'Receita',
    dashboard_customers: 'Clientes',
    dashboard_avg_order: 'Pedido médio',
    dashboard_recent_orders: 'Pedidos recentes',
    dashboard_low_stock: 'Estoque baixo',
    pos_title: 'Ponto de Venda',
    pos_search: 'Buscar itens...',
    pos_order_summary: 'Resumo do pedido',
    pos_total: 'Total',
    pos_place_order: 'Fazer pedido',
    pos_clear: 'Limpar',
    pos_categories: 'Categorias',
    kds_title: 'Display da Cozinha',
    kds_new: 'Novo',
    kds_preparing: 'Preparando',
    kds_ready: 'Pronto',
    kds_mark_ready: 'Marcar como pronto',
    inventory_title: 'Estoque',
    inventory_add_item: 'Adicionar item',
    inventory_search: 'Buscar estoque...',
    inventory_item_name: 'Nome do item',
    inventory_quantity: 'Quantidade',
    inventory_unit: 'Unidade',
    inventory_low_stock: 'Estoque baixo',
    bookings_title: 'Minhas Reservas',
    bookings_upcoming: 'Próximas',
    bookings_past: 'Passadas',
    bookings_cancel: 'Cancelar',
    bookings_no_bookings: 'Nenhuma reserva encontrada',
    careers_title: 'Carreiras',
    careers_subtitle: 'Junte-se à Nossa Equipe',
    careers_apply: 'Candidatar-se',
    careers_no_positions: 'Não há vagas disponíveis no momento.',
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    search: 'Buscar',
    add: 'Adicionar',
    update: 'Atualizar',
    confirm: 'Confirmar',
    back: 'Voltar',
    next: 'Próximo',
    close: 'Fechar',
    yes: 'Sim',
    no: 'Não',
  },

  ru: {
    nav_about: 'О нас',
    nav_menu: 'Меню',
    nav_reservations: 'Бронирование',
    nav_gallery: 'Галерея',
    nav_contact: 'Контакты',
    nav_careers: 'Вакансии',
    nav_home: 'Главная',
    nav_order: 'Заказ',
    nav_offers: 'Акции',
    nav_sign_in: 'Войти',
    nav_create_account: 'Создать аккаунт',
    nav_my_bookings: 'Мои бронирования',
    nav_rate_us: 'Оценить нас',
    nav_client_view: 'Вид клиента',
    nav_dashboard: 'Панель',
    nav_kds: 'KDS',
    nav_inventory: 'Инвентарь',
    nav_bookings: 'Бронирования',
    nav_specialties: 'Специальности',
    nav_orders: 'Заказы',
    nav_employees: 'Сотрудники',
    nav_admin_console: 'Консоль администратора',
    nav_sign_out: 'Выйти',
    nav_reset_system: 'Сброс системы',
    portal_admin: 'Портал администратора',
    portal_staff: 'Портал сотрудников',
    footer_navigate: 'Навигация',
    footer_hours: 'Часы работы',
    footer_newsletter: 'Рассылка',
    footer_newsletter_desc: 'Получайте эксклюзивные предложения и приглашения на события.',
    footer_email_placeholder: 'Email адрес',
    footer_join: 'Подписаться',
    footer_copyright: '© 2026 Kolay Restaurant. Все права защищены.',
    footer_privacy: 'Политика конфиденциальности',
    footer_terms: 'Условия использования',
    footer_staff_portal: 'Портал сотрудников',
    footer_language: 'Язык',
    footer_every_day: 'Каждый день',
    footer_open_247: 'Открыто 24/7',
    footer_tagline: 'Изысканные кулинарные впечатления для тех, кто ценит лучшее в жизни.',
    home_hero_subtitle: 'Необыкновенное кулинарное путешествие',
    home_hero_title_1: 'Где каждое блюдо',
    home_hero_title_2: 'рассказывает историю',
    home_hero_desc: 'Испытайте идеальную гармонию вкусов, атмосферы и сервиса. Мы создаём воспоминания на всю жизнь.',
    home_reserve_table: 'Забронировать стол',
    home_explore_menu: 'Изучить меню',
    home_guests_served: 'Обслуженных гостей',
    home_years_excellence: 'Лет совершенства',
    home_awards_won: 'Полученных наград',
    home_chefs: 'Мастер-шефов',
    about_title: 'Наша история',
    about_subtitle: 'Наследие кулинарного мастерства',
    about_desc_1: 'Основанный с любовью к изысканной кухне, Kolay Restaurant является символом изысканного ресторанного опыта с момента своего основания.',
    about_desc_2: 'Наши шеф-повара добывают лучшие ингредиенты со всего мира, сочетая традиционные техники с современными инновациями.',
    about_award: 'Ресторан со звездой Мишлен',
    about_commitment: 'Наше обязательство',
    about_commitment_desc: 'Мы верим, что каждый прием пищи должен быть незабываемым опытом. От свежих фермерских продуктов до тщательной подачи, совершенство - наше обещание.',
    menu_title: 'Наше меню',
    menu_subtitle: 'Кулинарные шедевры',
    menu_explore: 'Просмотреть полное меню',
    menu_order_online: 'Заказать онлайн',
    gallery_title: 'Галерея',
    gallery_subtitle: 'Визуальный пир',
    reservations_title: 'Бронирование',
    reservations_subtitle: 'Забронируйте стол',
    reservation_name: 'Полное имя',
    reservation_email: 'Email адрес',
    reservation_phone: 'Номер телефона',
    reservation_date: 'Дата',
    reservation_time: 'Время',
    reservation_guests: 'Количество гостей',
    reservation_notes: 'Особые пожелания',
    reservation_submit: 'Забронировать стол',
    reservation_success: 'Бронирование подтверждено!',
    reservation_select_guests: 'Выберите гостей',
    login_title: 'Добро пожаловать',
    login_subtitle: 'Войдите в аккаунт',
    login_email: 'Email',
    login_password: 'Пароль',
    login_btn: 'Войти',
    login_no_account: 'Нет аккаунта?',
    login_register: 'Создайте',
    register_title: 'Создать аккаунт',
    register_subtitle: 'Присоединитесь к Kolay Restaurant',
    register_username: 'Имя пользователя',
    register_email: 'Email',
    register_password: 'Пароль',
    register_confirm: 'Подтвердить пароль',
    register_btn: 'Создать аккаунт',
    register_have_account: 'Уже есть аккаунт?',
    register_sign_in: 'Войти',
    dashboard_title: 'Панель управления',
    dashboard_total_orders: 'Всего заказов',
    dashboard_revenue: 'Выручка',
    dashboard_customers: 'Клиенты',
    dashboard_avg_order: 'Средний заказ',
    dashboard_recent_orders: 'Последние заказы',
    dashboard_low_stock: 'Низкий запас',
    pos_title: 'Точка продаж',
    pos_search: 'Поиск...',
    pos_order_summary: 'Итог заказа',
    pos_total: 'Итого',
    pos_place_order: 'Оформить заказ',
    pos_clear: 'Очистить',
    pos_categories: 'Категории',
    kds_title: 'Кухонный дисплей',
    kds_new: 'Новый',
    kds_preparing: 'Готовится',
    kds_ready: 'Готово',
    kds_mark_ready: 'Отметить готовым',
    inventory_title: 'Инвентарь',
    inventory_add_item: 'Добавить товар',
    inventory_search: 'Поиск...',
    inventory_item_name: 'Название',
    inventory_quantity: 'Количество',
    inventory_unit: 'Единица',
    inventory_low_stock: 'Мало запасов',
    bookings_title: 'Мои бронирования',
    bookings_upcoming: 'Предстоящие',
    bookings_past: 'Прошедшие',
    bookings_cancel: 'Отменить',
    bookings_no_bookings: 'Бронирования не найдены',
    careers_title: 'Вакансии',
    careers_subtitle: 'Присоединитесь к нашей команде',
    careers_apply: 'Подать заявку',
    careers_no_positions: 'Нет открытых вакансий.',
    loading: 'Загрузка...',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Изменить',
    search: 'Поиск',
    add: 'Добавить',
    update: 'Обновить',
    confirm: 'Подтвердить',
    back: 'Назад',
    next: 'Далее',
    close: 'Закрыть',
    yes: 'Да',
    no: 'Нет',
  },

  ur: {
    nav_about: 'ہمارے بارے میں',
    nav_menu: 'مینو',
    nav_reservations: 'بکنگ',
    nav_gallery: 'گیلری',
    nav_contact: 'رابطہ کریں',
    nav_careers: 'ملازمتیں',
    nav_home: 'ہوم',
    nav_order: 'آرڈر',
    nav_offers: 'آفرز',
    nav_sign_in: 'سائن ان',
    nav_create_account: 'اکاؤنٹ بنائیں',
    nav_my_bookings: 'میری بکنگز',
    nav_rate_us: 'ہمیں ریٹ کریں',
    nav_client_view: 'کلائنٹ ویو',
    nav_dashboard: 'ڈیش بورڈ',
    nav_kds: 'KDS',
    nav_inventory: 'انوینٹری',
    nav_bookings: 'بکنگز',
    nav_specialties: 'خصوصیات',
    nav_orders: 'آرڈرز',
    nav_employees: 'ملازمین',
    nav_admin_console: 'ایڈمن کنسول',
    nav_sign_out: 'سائن آؤٹ',
    nav_reset_system: 'سسٹم ری سیٹ',
    portal_admin: 'ایڈمن پورٹل',
    portal_staff: 'اسٹاف پورٹل',
    footer_navigate: 'نیویگیٹ',
    footer_hours: 'اوقات',
    footer_newsletter: 'نیوزلیٹر',
    footer_newsletter_desc: 'خصوصی آفرز اور تقریبات کی دعوتیں حاصل کریں۔',
    footer_email_placeholder: 'ای میل پتہ',
    footer_join: 'شامل ہوں',
    footer_copyright: '© 2026 Kolay Restaurant۔ جملہ حقوق محفوظ ہیں۔',
    footer_privacy: 'رازداری کی پالیسی',
    footer_terms: 'استعمال کی شرائط',
    footer_staff_portal: 'اسٹاف پورٹل',
    footer_language: 'زبان',
    footer_every_day: 'ہر روز',
    footer_open_247: '24/7 کھلا',
    footer_tagline: 'زندگی کی بہترین چیزوں کی قدر کرنے والوں کے لیے تیار کردہ غیر معمولی پاکیزہ تجربات۔',
    home_hero_subtitle: 'ایک غیر معمولی پکوان سفر',
    home_hero_title_1: 'جہاں ہر ڈش',
    home_hero_title_2: 'ایک کہانی سناتی ہے',
    home_hero_desc: 'ذائقوں، ماحول اور خدمت کی مکمل ہم آہنگی کا تجربہ کریں۔ ہم زندگی بھر کی یادیں بناتے ہیں۔',
    home_reserve_table: 'میز بک کریں',
    home_explore_menu: 'مینو دیکھیں',
    home_guests_served: 'مہمان خدمت کیے',
    home_years_excellence: 'برسوں کی عمدگی',
    home_awards_won: 'انعامات جیتے',
    home_chefs: 'ماہر باورچی',
    about_title: 'ہماری کہانی',
    about_subtitle: 'پکوان عمدگی کی میراث',
    about_desc_1: 'غیر معمولی پکوان کے جنون کے ساتھ قائم، Kolay Restaurant اپنے آغاز سے ہی عمدہ کھانے کا ستون رہا ہے۔',
    about_desc_2: 'ہمارے باورچی دنیا بھر سے بہترین اجزاء حاصل کرتے ہیں، روایتی تکنیکوں کو جدید اختراع کے ساتھ ملا کر ناقابل فراموش کھانے کے تجربات بناتے ہیں۔',
    about_award: 'میشلن اسٹار ریستوراں',
    about_commitment: 'ہمارا عہد',
    about_commitment_desc: 'ہم مانتے ہیں کہ ہر کھانا ایک تجربہ ہونا چاہیے۔ تازہ اجزاء سے لے کر محتاط پیشکش تک، عمدگی ہمارا وعدہ ہے۔',
    menu_title: 'ہمارا مینو',
    menu_subtitle: 'پکوان شاہکار',
    menu_explore: 'مکمل مینو دیکھیں',
    menu_order_online: 'آن لائن آرڈر کریں',
    gallery_title: 'گیلری',
    gallery_subtitle: 'بصری ضیافت',
    reservations_title: 'بکنگ',
    reservations_subtitle: 'اپنی میز بک کریں',
    reservation_name: 'پورا نام',
    reservation_email: 'ای میل پتہ',
    reservation_phone: 'فون نمبر',
    reservation_date: 'تاریخ',
    reservation_time: 'وقت',
    reservation_guests: 'مہمانوں کی تعداد',
    reservation_notes: 'خصوصی درخواستیں',
    reservation_submit: 'میز بک کریں',
    reservation_success: 'بکنگ کی تصدیق ہوگئی!',
    reservation_select_guests: 'مہمان منتخب کریں',
    login_title: 'دوبارہ خوش آمدید',
    login_subtitle: 'اپنے اکاؤنٹ میں سائن ان کریں',
    login_email: 'ای میل',
    login_password: 'پاس ورڈ',
    login_btn: 'سائن ان',
    login_no_account: 'اکاؤنٹ نہیں ہے؟',
    login_register: 'بنائیں',
    register_title: 'اکاؤنٹ بنائیں',
    register_subtitle: 'Kolay Restaurant میں شامل ہوں',
    register_username: 'صارف نام',
    register_email: 'ای میل',
    register_password: 'پاس ورڈ',
    register_confirm: 'پاس ورڈ تصدیق کریں',
    register_btn: 'اکاؤنٹ بنائیں',
    register_have_account: 'پہلے سے اکاؤنٹ ہے؟',
    register_sign_in: 'سائن ان',
    dashboard_title: 'ڈیش بورڈ',
    dashboard_total_orders: 'کل آرڈرز',
    dashboard_revenue: 'آمدنی',
    dashboard_customers: 'گاہک',
    dashboard_avg_order: 'اوسط آرڈر',
    dashboard_recent_orders: 'حالیہ آرڈرز',
    dashboard_low_stock: 'کم اسٹاک',
    pos_title: 'پوائنٹ آف سیل',
    pos_search: 'آئٹمز تلاش کریں...',
    pos_order_summary: 'آرڈر خلاصہ',
    pos_total: 'کل',
    pos_place_order: 'آرڈر دیں',
    pos_clear: 'صاف کریں',
    pos_categories: 'زمرے',
    kds_title: 'کچن ڈسپلے',
    kds_new: 'نیا',
    kds_preparing: 'تیار ہو رہا ہے',
    kds_ready: 'تیار',
    kds_mark_ready: 'تیار نشان لگائیں',
    inventory_title: 'انوینٹری',
    inventory_add_item: 'آئٹم شامل کریں',
    inventory_search: 'انوینٹری تلاش کریں...',
    inventory_item_name: 'آئٹم کا نام',
    inventory_quantity: 'مقدار',
    inventory_unit: 'اکائی',
    inventory_low_stock: 'کم اسٹاک',
    bookings_title: 'میری بکنگز',
    bookings_upcoming: 'آنے والی',
    bookings_past: 'گزری',
    bookings_cancel: 'منسوخ',
    bookings_no_bookings: 'کوئی بکنگ نہیں ملی',
    careers_title: 'ملازمتیں',
    careers_subtitle: 'ہماری ٹیم میں شامل ہوں',
    careers_apply: 'ابھی درخواست دیں',
    careers_no_positions: 'اس وقت کوئی خالی عہدہ نہیں۔',
    loading: 'لوڈ ہو رہا ہے...',
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    delete: 'حذف کریں',
    edit: 'ترمیم',
    search: 'تلاش',
    add: 'شامل کریں',
    update: 'اپ ڈیٹ',
    confirm: 'تصدیق کریں',
    back: 'پیچھے',
    next: 'اگلا',
    close: 'بند کریں',
    yes: 'ہاں',
    no: 'نہیں',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('kolay_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kolay_language', language);
    const lang = LANGUAGES.find(l => l.code === language);
    if (lang) {
      document.documentElement.dir = lang.dir;
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key) => {
    const dict = translations[language] || translations['en'];
    return dict[key] ?? translations['en'][key] ?? key;
  };

  const currentLang = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLang, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
};

export default LanguageContext;
